### ISSUE TITLE
Fallout 4 Error

### ISSUE THREAD

**Issue by spentcasing** [qsniyg/ksp_stuff#16]
I run `python movfs4l.py --mo_installroot ~/.wine/drive_c/Games/MO2
* Generating configuration file
 -> Detected game `Fallout 4' at /home/shawn/.wine/dosdevices/c:/Games/Steam/steamapps/common/Fallout 4
* Written auto-generated configuration to `config.ini'. Please check the file, then run this script again.
* You can also re-run this for other installations by using `--generate_config'`

Everything is ok so far, next
`./movfs4l.py --game Fallout4
* Parsing configuration file
Traceback (most recent call last):
  File "./movfs4l.py", line 1040, in <module>
    game = games[game]
KeyError: 'Fallout4'
`

Here is my config.ini  http://dpaste.com/3K89EF2

**Comment by qsniyg** [comment]
Try:

    ./movfs4l.py --game "Fallout 4"

**Comment by spentcasing** [comment]
> * Parsing configuration file

* Using profile `Default'
* Removing VFS layer
 -> Reading VFS meta log
 -> Removing links
 -> Removing directories
 -> Restoring backups
 -> Clearing log
* Parsing MO mods configuration
* Creating VFS index
* Linking mods                                                                                                                                       
* Linking plugins list                                                                                                                               
* Linking load order
* Linking INI configuration files
* Writing log

* VFS layer created. Run "./movfs4l.py --game Fallout 4 --profile Default --unvfs" to shut it down (run this before running Mod Organizer again)`

Looks like it worked.  The line to shut it down also needs quotes around "Fallout 4"

**Comment by qsniyg** [comment]
@spentcasing Thanks! I'll fix that
