### ISSUE TITLE
Create fake .inis per ESP

### ISSUE THREAD

**Issue by qsniyg** [qsniyg/ksp_stuff#18]
This could potentially significantly improve the initial loading time, by reducing the amount of lookups required.

1) Create the in-memory mod VFS
2) Check for each ESM/ESP, and see if a .ini of the same name exists (e.g. RaceMenu.esp -> RaceMenu.ini)
3) If not, symlink to /dev/null

I haven't tried this, but in theory, it should work.

**Comment by qsniyg** [comment]
[PROFILE_Open](https://github.com/wine-mirror/wine/blob/ba9f3dc198dfc81bb40159077b73b797006bb73c/dlls/kernel32/profile.c#L790) in the wine source code strongly suggests doing this would help (and also suggests this issue might not actually appear under Windows). If the .ini file is successfully opened, it seems like it will not try to open it again.

**Comment by ajspandigital** [comment]
I'll try test this code tomorrow, and get some timings on it, and if I'm happy it doesn't break anything and adds value I'll merge it.

**Comment by ajventer** [comment]
Oh wait, this is an issue, not a PR yet. So nothing to test yet.

Sorry, my bad.

**Comment by qsniyg** [comment]
No worries, I'm just waiting until I manage to finish winevfs before working on this :)

**Comment by qsniyg** [comment]
This appears to cause issues when running FNIS. Running it with pure Skyrim seems to work however.

Perhaps a better solution would be to actually create blank files

**Comment by qsniyg** [comment]
An actual solution is to use this mod: https://www.nexusmods.com/skyrim/mods/92725?tab=files
