### ISSUE TITLE
Any plan for MO2 support?

### ISSUE THREAD

**Issue by Nanodragon999** [qsniyg/ksp_stuff#29]
So as you might know, this script work well with MO 1.33 but sadly doesn't seem to work on more recent version (MO2), which is needed if say, you want to use it with fallout 4 or SkyrimSE.

**Comment by qsniyg** [comment]
Weird, I've only tested it on MO2 actually, and it does work for FO4 for me... could you share the configuration file, and elaborate a little more on what doesn't work?

**Comment by Nanodragon999** [comment]
So, i tried using 
```WINEPREFIX="/home/nordmagnus/.steam/steam/steamapps/compatdata/489830/pfx" ksp_stuff/movfs4l.py --mo_installroot ~/.steam/debian-installation/steamapps/common/Skyrim\ Special\ Edition/Mod.Organizer.2.1.3/ --wineuser steamuser --winevfs winevfs/bin/winevfs UNFVS```

it throw an error such as this: ```FileNotFoundError: [Errno 2] No such file or directory: '/home/nordmagnus/.steam/steam/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/Local Settings/Application Data/ModOrganizer/SkyrimSE/profiles/Default/skyrim.ini' -> '/home/nordmagnus/.steam/steam/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/My Documents/My Games/SkyrimSE/skyrim.ini'```
after generating the config of course, (btw, using steam + proton GE build on ubuntu 64bit with nvidia and intel).

**Comment by qsniyg** [comment]
@Nanodragon999 A few notes:

 * Avoid using winevfs, I should probably write a note about it. It's horribly broken haha, and the proper solution (fixing USVFS) has already been done, so there's no need for it :)
 * The `UNVFS` option has been replaced to `--unvfs`
 * Could you send me the generated config file? And could you share me a directory listing of `/home/nordmagnus/.steam/steam/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/Local Settings/Application Data/ModOrganizer/` and `/home/nordmagnus/.steam/steam/steamapps/compatdata/489830/pfx/drive_c/users/steamuser/My Documents/My Games/`?

**Comment by Nanodragon999** [comment]
Gotcha, i didn't know that part about winevfs :)
here the generated [config.ini](https://pastebin.com/raw/PT2z9WVZ)
and here the directory listing for the first [path](https://pastebin.com/raw/jCJXRpnk) and the [second one](https://pastebin.com/raw/Y958p53a).

**Comment by qsniyg** [comment]
@Nanodragon999 Try updating the repo, it should have fixed the path :)

**Comment by Nanodragon999** [comment]
yeah, seems it work now :) (although there another non-related issue, will open another one if you don't mind)

**Comment by qsniyg** [comment]
Awesome, and yeah absolutely :)
